// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iyag.io/chat/entry.proto

package chat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Entry struct {
	Meta                 *EntryMeta    `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	Content              *EntryContent `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_entry_d3105bface7bd471, []int{0}
}
func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (dst *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(dst, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetMeta() *EntryMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Entry) GetContent() *EntryContent {
	if m != nil {
		return m.Content
	}
	return nil
}

type EntryMeta struct {
	// specified by the client when they send a entry, for deduplication purpose
	Uuid string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	// Name of the channel where the entry goes
	ChannelName string `protobuf:"bytes,2,opt,name=channel_name,json=channelName" json:"channel_name,omitempty"`
	// if set, points to the UUID that starts the thread
	ThreadUuid string `protobuf:"bytes,3,opt,name=thread_uuid,json=threadUuid" json:"thread_uuid,omitempty"`
	// ID of the author who sent the entry.
	AuthorId string `protobuf:"bytes,4,opt,name=author_id,json=authorId" json:"author_id,omitempty"`
	// time when the entry was sent (client side), updated when the server accepts it
	Time *timestamp.Timestamp `protobuf:"bytes,5,opt,name=time" json:"time,omitempty"`
	// sequence in which the message was received by the server
	Sequence             uint64   `protobuf:"varint,6,opt,name=sequence" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryMeta) Reset()         { *m = EntryMeta{} }
func (m *EntryMeta) String() string { return proto.CompactTextString(m) }
func (*EntryMeta) ProtoMessage()    {}
func (*EntryMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_entry_d3105bface7bd471, []int{1}
}
func (m *EntryMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryMeta.Unmarshal(m, b)
}
func (m *EntryMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryMeta.Marshal(b, m, deterministic)
}
func (dst *EntryMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryMeta.Merge(dst, src)
}
func (m *EntryMeta) XXX_Size() int {
	return xxx_messageInfo_EntryMeta.Size(m)
}
func (m *EntryMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryMeta.DiscardUnknown(m)
}

var xxx_messageInfo_EntryMeta proto.InternalMessageInfo

func (m *EntryMeta) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EntryMeta) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *EntryMeta) GetThreadUuid() string {
	if m != nil {
		return m.ThreadUuid
	}
	return ""
}

func (m *EntryMeta) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *EntryMeta) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *EntryMeta) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

type EntryContent struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryContent) Reset()         { *m = EntryContent{} }
func (m *EntryContent) String() string { return proto.CompactTextString(m) }
func (*EntryContent) ProtoMessage()    {}
func (*EntryContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_entry_d3105bface7bd471, []int{2}
}
func (m *EntryContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryContent.Unmarshal(m, b)
}
func (m *EntryContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryContent.Marshal(b, m, deterministic)
}
func (dst *EntryContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryContent.Merge(dst, src)
}
func (m *EntryContent) XXX_Size() int {
	return xxx_messageInfo_EntryContent.Size(m)
}
func (m *EntryContent) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryContent.DiscardUnknown(m)
}

var xxx_messageInfo_EntryContent proto.InternalMessageInfo

func (m *EntryContent) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*Entry)(nil), "iyag.io.chat.Entry")
	proto.RegisterType((*EntryMeta)(nil), "iyag.io.chat.EntryMeta")
	proto.RegisterType((*EntryContent)(nil), "iyag.io.chat.EntryContent")
}

func init() { proto.RegisterFile("iyag.io/chat/entry.proto", fileDescriptor_entry_d3105bface7bd471) }

var fileDescriptor_entry_d3105bface7bd471 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4e, 0xfb, 0x30,
	0x10, 0xc6, 0x95, 0xff, 0xdf, 0x2d, 0xcd, 0x35, 0x93, 0x17, 0xac, 0x30, 0xb4, 0x64, 0xaa, 0x84,
	0xe4, 0x48, 0xc0, 0x13, 0x80, 0x18, 0x18, 0x60, 0xb0, 0x60, 0x61, 0x89, 0x9c, 0xe4, 0x48, 0x82,
	0x1a, 0xbb, 0xa4, 0xce, 0x90, 0x77, 0xe4, 0xa1, 0x90, 0x2f, 0x49, 0xd5, 0x81, 0xed, 0x7c, 0xdf,
	0xef, 0xbe, 0xf3, 0x7d, 0x20, 0x9a, 0x41, 0x57, 0xb2, 0xb1, 0x69, 0x51, 0x6b, 0x97, 0xa2, 0x71,
	0xdd, 0x20, 0x0f, 0x9d, 0x75, 0x96, 0x47, 0x93, 0x22, 0xbd, 0x12, 0x6f, 0x2a, 0x6b, 0xab, 0x3d,
	0xa6, 0xa4, 0xe5, 0xfd, 0x67, 0xea, 0x9a, 0x16, 0x8f, 0x4e, 0xb7, 0x87, 0x11, 0x4f, 0xbe, 0x60,
	0xf1, 0xe4, 0xa7, 0xf9, 0x0d, 0xb0, 0x16, 0x9d, 0x16, 0xc1, 0x36, 0xd8, 0xad, 0x6f, 0x2f, 0xe5,
	0xb9, 0x8d, 0x24, 0xe4, 0x05, 0x9d, 0x56, 0x04, 0xf1, 0x7b, 0xb8, 0x28, 0xac, 0x71, 0x68, 0x9c,
	0xf8, 0x47, 0x7c, 0xfc, 0x07, 0xff, 0x38, 0x12, 0x6a, 0x46, 0x93, 0x9f, 0x00, 0xc2, 0x93, 0x13,
	0xe7, 0xc0, 0xfa, 0xbe, 0x29, 0x69, 0x61, 0xa8, 0xa8, 0xe6, 0xd7, 0x10, 0x15, 0xb5, 0x36, 0x06,
	0xf7, 0x99, 0xd1, 0x2d, 0x92, 0x79, 0xa8, 0xd6, 0x53, 0xef, 0x55, 0xb7, 0xc8, 0x37, 0xb0, 0x76,
	0x75, 0x87, 0xba, 0xcc, 0x68, 0xfa, 0x3f, 0x11, 0x30, 0xb6, 0xde, 0xbd, 0xc7, 0x15, 0x84, 0xba,
	0x77, 0xb5, 0xed, 0xb2, 0xa6, 0x14, 0x8c, 0xe4, 0xd5, 0xd8, 0x78, 0x2e, 0xb9, 0x04, 0xe6, 0x13,
	0x10, 0x8b, 0xe9, 0xd7, 0x63, 0x3c, 0x72, 0x8e, 0x47, 0xbe, 0xcd, 0xf1, 0x28, 0xe2, 0x78, 0x0c,
	0xab, 0x23, 0x7e, 0xf7, 0x68, 0x0a, 0x14, 0xcb, 0x6d, 0xb0, 0x63, 0xea, 0xf4, 0x4e, 0x12, 0x88,
	0xce, 0xef, 0xf4, 0x07, 0xe5, 0xb6, 0x1c, 0xe6, 0x83, 0x7c, 0xfd, 0xb0, 0xfc, 0x60, 0x3e, 0x90,
	0x7c, 0x49, 0x1b, 0xee, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x99, 0xb4, 0x2f, 0xe4, 0xb8, 0x01,
	0x00, 0x00,
}
