// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iyag.io/chat/entry.proto

package chat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Entry struct {
	Meta                 *EntryMeta    `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	Content              *EntryContent `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_entry_5573e1544a880c1d, []int{0}
}
func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (dst *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(dst, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetMeta() *EntryMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Entry) GetContent() *EntryContent {
	if m != nil {
		return m.Content
	}
	return nil
}

type EntryMeta struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	ChannelId            string               `protobuf:"bytes,2,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	ThreadId             string               `protobuf:"bytes,3,opt,name=thread_id,json=threadId" json:"thread_id,omitempty"`
	AuthorId             string               `protobuf:"bytes,4,opt,name=author_id,json=authorId" json:"author_id,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,5,opt,name=time" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EntryMeta) Reset()         { *m = EntryMeta{} }
func (m *EntryMeta) String() string { return proto.CompactTextString(m) }
func (*EntryMeta) ProtoMessage()    {}
func (*EntryMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_entry_5573e1544a880c1d, []int{1}
}
func (m *EntryMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryMeta.Unmarshal(m, b)
}
func (m *EntryMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryMeta.Marshal(b, m, deterministic)
}
func (dst *EntryMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryMeta.Merge(dst, src)
}
func (m *EntryMeta) XXX_Size() int {
	return xxx_messageInfo_EntryMeta.Size(m)
}
func (m *EntryMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryMeta.DiscardUnknown(m)
}

var xxx_messageInfo_EntryMeta proto.InternalMessageInfo

func (m *EntryMeta) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EntryMeta) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *EntryMeta) GetThreadId() string {
	if m != nil {
		return m.ThreadId
	}
	return ""
}

func (m *EntryMeta) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *EntryMeta) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type EntryContent struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryContent) Reset()         { *m = EntryContent{} }
func (m *EntryContent) String() string { return proto.CompactTextString(m) }
func (*EntryContent) ProtoMessage()    {}
func (*EntryContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_entry_5573e1544a880c1d, []int{2}
}
func (m *EntryContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryContent.Unmarshal(m, b)
}
func (m *EntryContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryContent.Marshal(b, m, deterministic)
}
func (dst *EntryContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryContent.Merge(dst, src)
}
func (m *EntryContent) XXX_Size() int {
	return xxx_messageInfo_EntryContent.Size(m)
}
func (m *EntryContent) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryContent.DiscardUnknown(m)
}

var xxx_messageInfo_EntryContent proto.InternalMessageInfo

func (m *EntryContent) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*Entry)(nil), "iyag.io.chat.Entry")
	proto.RegisterType((*EntryMeta)(nil), "iyag.io.chat.EntryMeta")
	proto.RegisterType((*EntryContent)(nil), "iyag.io.chat.EntryContent")
}

func init() { proto.RegisterFile("iyag.io/chat/entry.proto", fileDescriptor_entry_5573e1544a880c1d) }

var fileDescriptor_entry_5573e1544a880c1d = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xa9, 0x66, 0x57, 0x33, 0xee, 0x29, 0x17, 0xcb, 0x8a, 0x28, 0x3d, 0x09, 0x42, 0x0a,
	0xea, 0x13, 0x28, 0x1e, 0xf6, 0xe0, 0x25, 0x78, 0xf2, 0x22, 0x69, 0x13, 0xdb, 0xc8, 0x36, 0x59,
	0xea, 0xf4, 0xd0, 0x37, 0xf2, 0x31, 0x25, 0x93, 0x56, 0x7a, 0xd8, 0xdb, 0x30, 0xdf, 0x97, 0x3f,
	0x33, 0x03, 0xb9, 0x1b, 0x75, 0x23, 0x5d, 0x28, 0xeb, 0x56, 0x63, 0x69, 0x3d, 0xf6, 0xa3, 0x3c,
	0xf4, 0x01, 0x83, 0xd8, 0x4c, 0x44, 0x46, 0xb2, 0xbd, 0x69, 0x42, 0x68, 0xf6, 0xb6, 0x24, 0x56,
	0x0d, 0x5f, 0x25, 0xba, 0xce, 0xfe, 0xa0, 0xee, 0x0e, 0x49, 0x2f, 0xbe, 0x61, 0xf5, 0x1a, 0x5f,
	0x8b, 0x7b, 0x60, 0x9d, 0x45, 0x9d, 0x67, 0xb7, 0xd9, 0xdd, 0xc5, 0xc3, 0xa5, 0x5c, 0xc6, 0x48,
	0x52, 0xde, 0x2c, 0x6a, 0x45, 0x92, 0x78, 0x82, 0xb3, 0x3a, 0x78, 0xb4, 0x1e, 0xf3, 0x13, 0xf2,
	0xb7, 0x47, 0xfc, 0x97, 0x64, 0xa8, 0x59, 0x2d, 0x7e, 0x33, 0xe0, 0xff, 0x49, 0x42, 0x00, 0x1b,
	0x06, 0x67, 0xe8, 0x43, 0xae, 0xa8, 0x16, 0xd7, 0x00, 0x75, 0xab, 0xbd, 0xb7, 0xfb, 0x4f, 0x67,
	0x28, 0x9a, 0x2b, 0x3e, 0x75, 0x76, 0x46, 0x5c, 0x01, 0xc7, 0xb6, 0xb7, 0xda, 0x44, 0x7a, 0x4a,
	0xf4, 0x3c, 0x35, 0x12, 0xd4, 0x03, 0xb6, 0xa1, 0x8f, 0x90, 0x25, 0x98, 0x1a, 0x3b, 0x23, 0x24,
	0xb0, 0xb8, 0x79, 0xbe, 0x9a, 0xa6, 0x4d, 0x67, 0x91, 0xf3, 0x59, 0xe4, 0xfb, 0x7c, 0x16, 0x45,
	0x5e, 0x51, 0xc0, 0x66, 0xb9, 0x43, 0x1c, 0xb6, 0x0a, 0x66, 0x9c, 0x87, 0x8d, 0xf5, 0xf3, 0xfa,
	0x83, 0xc5, 0x65, 0xab, 0x35, 0xa5, 0x3c, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x04, 0xbe, 0x41,
	0x55, 0x94, 0x01, 0x00, 0x00,
}
