// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iyag.io/chat/event.proto

package chat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EventMeta struct {
	// specified by the client when they send a entry, for deduplication purpose
	Uuid string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	// time when the event was sent (client side), updated when the server accepts it
	Time *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time" json:"time,omitempty"`
	// sequence in which the event was received by the server
	Sequence             uint64   `protobuf:"varint,3,opt,name=sequence" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventMeta) Reset()         { *m = EventMeta{} }
func (m *EventMeta) String() string { return proto.CompactTextString(m) }
func (*EventMeta) ProtoMessage()    {}
func (*EventMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_1bfe42272c78c94b, []int{0}
}
func (m *EventMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventMeta.Unmarshal(m, b)
}
func (m *EventMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventMeta.Marshal(b, m, deterministic)
}
func (dst *EventMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMeta.Merge(dst, src)
}
func (m *EventMeta) XXX_Size() int {
	return xxx_messageInfo_EventMeta.Size(m)
}
func (m *EventMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMeta.DiscardUnknown(m)
}

var xxx_messageInfo_EventMeta proto.InternalMessageInfo

func (m *EventMeta) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EventMeta) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *EventMeta) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

type ChannelState struct {
	LastEvent            *EventMeta           `protobuf:"bytes,1,opt,name=last_event,json=lastEvent" json:"last_event,omitempty"`
	Entries              []*Entry             `protobuf:"bytes,2,rep,name=entries" json:"entries,omitempty"`
	AuthorIds            []string             `protobuf:"bytes,3,rep,name=author_ids,json=authorIds" json:"author_ids,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	ArchivedAt           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=archived_at,json=archivedAt" json:"archived_at,omitempty"`
	CreatedBy            string               `protobuf:"bytes,6,opt,name=created_by,json=createdBy" json:"created_by,omitempty"`
	ArchivedBy           string               `protobuf:"bytes,7,opt,name=archived_by,json=archivedBy" json:"archived_by,omitempty"`
	Name                 string               `protobuf:"bytes,8,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ChannelState) Reset()         { *m = ChannelState{} }
func (m *ChannelState) String() string { return proto.CompactTextString(m) }
func (*ChannelState) ProtoMessage()    {}
func (*ChannelState) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_1bfe42272c78c94b, []int{1}
}
func (m *ChannelState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelState.Unmarshal(m, b)
}
func (m *ChannelState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelState.Marshal(b, m, deterministic)
}
func (dst *ChannelState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelState.Merge(dst, src)
}
func (m *ChannelState) XXX_Size() int {
	return xxx_messageInfo_ChannelState.Size(m)
}
func (m *ChannelState) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelState.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelState proto.InternalMessageInfo

func (m *ChannelState) GetLastEvent() *EventMeta {
	if m != nil {
		return m.LastEvent
	}
	return nil
}

func (m *ChannelState) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *ChannelState) GetAuthorIds() []string {
	if m != nil {
		return m.AuthorIds
	}
	return nil
}

func (m *ChannelState) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ChannelState) GetArchivedAt() *timestamp.Timestamp {
	if m != nil {
		return m.ArchivedAt
	}
	return nil
}

func (m *ChannelState) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *ChannelState) GetArchivedBy() string {
	if m != nil {
		return m.ArchivedBy
	}
	return ""
}

func (m *ChannelState) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ChannelUserEvent struct {
	Meta        *EventMeta `protobuf:"bytes,100,opt,name=meta" json:"meta,omitempty"`
	ChannelName string     `protobuf:"bytes,101,opt,name=channel_name,json=channelName" json:"channel_name,omitempty"`
	AuthorId    string     `protobuf:"bytes,102,opt,name=author_id,json=authorId" json:"author_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//	*ChannelUserEvent_Created
	//	*ChannelUserEvent_Archived
	//	*ChannelUserEvent_Joined
	//	*ChannelUserEvent_Left
	//	*ChannelUserEvent_Typed
	//	*ChannelUserEvent_Sent
	Event                isChannelUserEvent_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ChannelUserEvent) Reset()         { *m = ChannelUserEvent{} }
func (m *ChannelUserEvent) String() string { return proto.CompactTextString(m) }
func (*ChannelUserEvent) ProtoMessage()    {}
func (*ChannelUserEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_1bfe42272c78c94b, []int{2}
}
func (m *ChannelUserEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelUserEvent.Unmarshal(m, b)
}
func (m *ChannelUserEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelUserEvent.Marshal(b, m, deterministic)
}
func (dst *ChannelUserEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelUserEvent.Merge(dst, src)
}
func (m *ChannelUserEvent) XXX_Size() int {
	return xxx_messageInfo_ChannelUserEvent.Size(m)
}
func (m *ChannelUserEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelUserEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelUserEvent proto.InternalMessageInfo

type isChannelUserEvent_Event interface {
	isChannelUserEvent_Event()
}

type ChannelUserEvent_Created struct {
	Created *ChannelUserEvent_Create `protobuf:"bytes,201,opt,name=created,oneof"`
}
type ChannelUserEvent_Archived struct {
	Archived *ChannelUserEvent_Archive `protobuf:"bytes,202,opt,name=archived,oneof"`
}
type ChannelUserEvent_Joined struct {
	Joined *ChannelUserEvent_Join `protobuf:"bytes,203,opt,name=joined,oneof"`
}
type ChannelUserEvent_Left struct {
	Left *ChannelUserEvent_Leave `protobuf:"bytes,204,opt,name=left,oneof"`
}
type ChannelUserEvent_Typed struct {
	Typed *ChannelUserEvent_Type `protobuf:"bytes,205,opt,name=typed,oneof"`
}
type ChannelUserEvent_Sent struct {
	Sent *ChannelUserEvent_Send `protobuf:"bytes,206,opt,name=sent,oneof"`
}

func (*ChannelUserEvent_Created) isChannelUserEvent_Event()  {}
func (*ChannelUserEvent_Archived) isChannelUserEvent_Event() {}
func (*ChannelUserEvent_Joined) isChannelUserEvent_Event()   {}
func (*ChannelUserEvent_Left) isChannelUserEvent_Event()     {}
func (*ChannelUserEvent_Typed) isChannelUserEvent_Event()    {}
func (*ChannelUserEvent_Sent) isChannelUserEvent_Event()     {}

func (m *ChannelUserEvent) GetEvent() isChannelUserEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *ChannelUserEvent) GetMeta() *EventMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ChannelUserEvent) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *ChannelUserEvent) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *ChannelUserEvent) GetCreated() *ChannelUserEvent_Create {
	if x, ok := m.GetEvent().(*ChannelUserEvent_Created); ok {
		return x.Created
	}
	return nil
}

func (m *ChannelUserEvent) GetArchived() *ChannelUserEvent_Archive {
	if x, ok := m.GetEvent().(*ChannelUserEvent_Archived); ok {
		return x.Archived
	}
	return nil
}

func (m *ChannelUserEvent) GetJoined() *ChannelUserEvent_Join {
	if x, ok := m.GetEvent().(*ChannelUserEvent_Joined); ok {
		return x.Joined
	}
	return nil
}

func (m *ChannelUserEvent) GetLeft() *ChannelUserEvent_Leave {
	if x, ok := m.GetEvent().(*ChannelUserEvent_Left); ok {
		return x.Left
	}
	return nil
}

func (m *ChannelUserEvent) GetTyped() *ChannelUserEvent_Type {
	if x, ok := m.GetEvent().(*ChannelUserEvent_Typed); ok {
		return x.Typed
	}
	return nil
}

func (m *ChannelUserEvent) GetSent() *ChannelUserEvent_Send {
	if x, ok := m.GetEvent().(*ChannelUserEvent_Sent); ok {
		return x.Sent
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ChannelUserEvent) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ChannelUserEvent_OneofMarshaler, _ChannelUserEvent_OneofUnmarshaler, _ChannelUserEvent_OneofSizer, []interface{}{
		(*ChannelUserEvent_Created)(nil),
		(*ChannelUserEvent_Archived)(nil),
		(*ChannelUserEvent_Joined)(nil),
		(*ChannelUserEvent_Left)(nil),
		(*ChannelUserEvent_Typed)(nil),
		(*ChannelUserEvent_Sent)(nil),
	}
}

func _ChannelUserEvent_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ChannelUserEvent)
	// event
	switch x := m.Event.(type) {
	case *ChannelUserEvent_Created:
		b.EncodeVarint(201<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Created); err != nil {
			return err
		}
	case *ChannelUserEvent_Archived:
		b.EncodeVarint(202<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Archived); err != nil {
			return err
		}
	case *ChannelUserEvent_Joined:
		b.EncodeVarint(203<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Joined); err != nil {
			return err
		}
	case *ChannelUserEvent_Left:
		b.EncodeVarint(204<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Left); err != nil {
			return err
		}
	case *ChannelUserEvent_Typed:
		b.EncodeVarint(205<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Typed); err != nil {
			return err
		}
	case *ChannelUserEvent_Sent:
		b.EncodeVarint(206<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Sent); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ChannelUserEvent.Event has unexpected type %T", x)
	}
	return nil
}

func _ChannelUserEvent_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ChannelUserEvent)
	switch tag {
	case 201: // event.created
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ChannelUserEvent_Create)
		err := b.DecodeMessage(msg)
		m.Event = &ChannelUserEvent_Created{msg}
		return true, err
	case 202: // event.archived
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ChannelUserEvent_Archive)
		err := b.DecodeMessage(msg)
		m.Event = &ChannelUserEvent_Archived{msg}
		return true, err
	case 203: // event.joined
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ChannelUserEvent_Join)
		err := b.DecodeMessage(msg)
		m.Event = &ChannelUserEvent_Joined{msg}
		return true, err
	case 204: // event.left
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ChannelUserEvent_Leave)
		err := b.DecodeMessage(msg)
		m.Event = &ChannelUserEvent_Left{msg}
		return true, err
	case 205: // event.typed
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ChannelUserEvent_Type)
		err := b.DecodeMessage(msg)
		m.Event = &ChannelUserEvent_Typed{msg}
		return true, err
	case 206: // event.sent
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ChannelUserEvent_Send)
		err := b.DecodeMessage(msg)
		m.Event = &ChannelUserEvent_Sent{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ChannelUserEvent_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ChannelUserEvent)
	// event
	switch x := m.Event.(type) {
	case *ChannelUserEvent_Created:
		s := proto.Size(x.Created)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ChannelUserEvent_Archived:
		s := proto.Size(x.Archived)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ChannelUserEvent_Joined:
		s := proto.Size(x.Joined)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ChannelUserEvent_Left:
		s := proto.Size(x.Left)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ChannelUserEvent_Typed:
		s := proto.Size(x.Typed)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ChannelUserEvent_Sent:
		s := proto.Size(x.Sent)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ChannelUserEvent_Create struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelUserEvent_Create) Reset()         { *m = ChannelUserEvent_Create{} }
func (m *ChannelUserEvent_Create) String() string { return proto.CompactTextString(m) }
func (*ChannelUserEvent_Create) ProtoMessage()    {}
func (*ChannelUserEvent_Create) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_1bfe42272c78c94b, []int{2, 0}
}
func (m *ChannelUserEvent_Create) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelUserEvent_Create.Unmarshal(m, b)
}
func (m *ChannelUserEvent_Create) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelUserEvent_Create.Marshal(b, m, deterministic)
}
func (dst *ChannelUserEvent_Create) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelUserEvent_Create.Merge(dst, src)
}
func (m *ChannelUserEvent_Create) XXX_Size() int {
	return xxx_messageInfo_ChannelUserEvent_Create.Size(m)
}
func (m *ChannelUserEvent_Create) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelUserEvent_Create.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelUserEvent_Create proto.InternalMessageInfo

func (m *ChannelUserEvent_Create) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ChannelUserEvent_Archive struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelUserEvent_Archive) Reset()         { *m = ChannelUserEvent_Archive{} }
func (m *ChannelUserEvent_Archive) String() string { return proto.CompactTextString(m) }
func (*ChannelUserEvent_Archive) ProtoMessage()    {}
func (*ChannelUserEvent_Archive) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_1bfe42272c78c94b, []int{2, 1}
}
func (m *ChannelUserEvent_Archive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelUserEvent_Archive.Unmarshal(m, b)
}
func (m *ChannelUserEvent_Archive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelUserEvent_Archive.Marshal(b, m, deterministic)
}
func (dst *ChannelUserEvent_Archive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelUserEvent_Archive.Merge(dst, src)
}
func (m *ChannelUserEvent_Archive) XXX_Size() int {
	return xxx_messageInfo_ChannelUserEvent_Archive.Size(m)
}
func (m *ChannelUserEvent_Archive) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelUserEvent_Archive.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelUserEvent_Archive proto.InternalMessageInfo

type ChannelUserEvent_Join struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelUserEvent_Join) Reset()         { *m = ChannelUserEvent_Join{} }
func (m *ChannelUserEvent_Join) String() string { return proto.CompactTextString(m) }
func (*ChannelUserEvent_Join) ProtoMessage()    {}
func (*ChannelUserEvent_Join) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_1bfe42272c78c94b, []int{2, 2}
}
func (m *ChannelUserEvent_Join) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelUserEvent_Join.Unmarshal(m, b)
}
func (m *ChannelUserEvent_Join) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelUserEvent_Join.Marshal(b, m, deterministic)
}
func (dst *ChannelUserEvent_Join) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelUserEvent_Join.Merge(dst, src)
}
func (m *ChannelUserEvent_Join) XXX_Size() int {
	return xxx_messageInfo_ChannelUserEvent_Join.Size(m)
}
func (m *ChannelUserEvent_Join) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelUserEvent_Join.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelUserEvent_Join proto.InternalMessageInfo

type ChannelUserEvent_Leave struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelUserEvent_Leave) Reset()         { *m = ChannelUserEvent_Leave{} }
func (m *ChannelUserEvent_Leave) String() string { return proto.CompactTextString(m) }
func (*ChannelUserEvent_Leave) ProtoMessage()    {}
func (*ChannelUserEvent_Leave) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_1bfe42272c78c94b, []int{2, 3}
}
func (m *ChannelUserEvent_Leave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelUserEvent_Leave.Unmarshal(m, b)
}
func (m *ChannelUserEvent_Leave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelUserEvent_Leave.Marshal(b, m, deterministic)
}
func (dst *ChannelUserEvent_Leave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelUserEvent_Leave.Merge(dst, src)
}
func (m *ChannelUserEvent_Leave) XXX_Size() int {
	return xxx_messageInfo_ChannelUserEvent_Leave.Size(m)
}
func (m *ChannelUserEvent_Leave) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelUserEvent_Leave.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelUserEvent_Leave proto.InternalMessageInfo

type ChannelUserEvent_Type struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelUserEvent_Type) Reset()         { *m = ChannelUserEvent_Type{} }
func (m *ChannelUserEvent_Type) String() string { return proto.CompactTextString(m) }
func (*ChannelUserEvent_Type) ProtoMessage()    {}
func (*ChannelUserEvent_Type) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_1bfe42272c78c94b, []int{2, 4}
}
func (m *ChannelUserEvent_Type) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelUserEvent_Type.Unmarshal(m, b)
}
func (m *ChannelUserEvent_Type) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelUserEvent_Type.Marshal(b, m, deterministic)
}
func (dst *ChannelUserEvent_Type) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelUserEvent_Type.Merge(dst, src)
}
func (m *ChannelUserEvent_Type) XXX_Size() int {
	return xxx_messageInfo_ChannelUserEvent_Type.Size(m)
}
func (m *ChannelUserEvent_Type) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelUserEvent_Type.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelUserEvent_Type proto.InternalMessageInfo

type ChannelUserEvent_Send struct {
	Entry                *Entry   `protobuf:"bytes,1,opt,name=entry" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelUserEvent_Send) Reset()         { *m = ChannelUserEvent_Send{} }
func (m *ChannelUserEvent_Send) String() string { return proto.CompactTextString(m) }
func (*ChannelUserEvent_Send) ProtoMessage()    {}
func (*ChannelUserEvent_Send) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_1bfe42272c78c94b, []int{2, 5}
}
func (m *ChannelUserEvent_Send) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelUserEvent_Send.Unmarshal(m, b)
}
func (m *ChannelUserEvent_Send) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelUserEvent_Send.Marshal(b, m, deterministic)
}
func (dst *ChannelUserEvent_Send) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelUserEvent_Send.Merge(dst, src)
}
func (m *ChannelUserEvent_Send) XXX_Size() int {
	return xxx_messageInfo_ChannelUserEvent_Send.Size(m)
}
func (m *ChannelUserEvent_Send) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelUserEvent_Send.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelUserEvent_Send proto.InternalMessageInfo

func (m *ChannelUserEvent_Send) GetEntry() *Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func init() {
	proto.RegisterType((*EventMeta)(nil), "iyag.io.chat.EventMeta")
	proto.RegisterType((*ChannelState)(nil), "iyag.io.chat.ChannelState")
	proto.RegisterType((*ChannelUserEvent)(nil), "iyag.io.chat.ChannelUserEvent")
	proto.RegisterType((*ChannelUserEvent_Create)(nil), "iyag.io.chat.ChannelUserEvent.Create")
	proto.RegisterType((*ChannelUserEvent_Archive)(nil), "iyag.io.chat.ChannelUserEvent.Archive")
	proto.RegisterType((*ChannelUserEvent_Join)(nil), "iyag.io.chat.ChannelUserEvent.Join")
	proto.RegisterType((*ChannelUserEvent_Leave)(nil), "iyag.io.chat.ChannelUserEvent.Leave")
	proto.RegisterType((*ChannelUserEvent_Type)(nil), "iyag.io.chat.ChannelUserEvent.Type")
	proto.RegisterType((*ChannelUserEvent_Send)(nil), "iyag.io.chat.ChannelUserEvent.Send")
}

func init() { proto.RegisterFile("iyag.io/chat/event.proto", fileDescriptor_event_1bfe42272c78c94b) }

var fileDescriptor_event_1bfe42272c78c94b = []byte{
	// 565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5d, 0x8f, 0xd2, 0x40,
	0x14, 0x5d, 0x60, 0x68, 0xe9, 0x85, 0x07, 0x73, 0x7d, 0x70, 0x52, 0x35, 0x8b, 0xf8, 0x11, 0x8c,
	0xb1, 0x44, 0x4c, 0x4c, 0x74, 0x8d, 0x09, 0x6c, 0x36, 0x41, 0xa3, 0x3e, 0x74, 0xd7, 0x17, 0x5f,
	0xc8, 0x40, 0x2f, 0x50, 0x85, 0x16, 0xdb, 0x61, 0x93, 0xfe, 0x44, 0x3f, 0x7f, 0x83, 0xff, 0x44,
	0x33, 0x33, 0x6d, 0x5d, 0x89, 0xb1, 0xfb, 0xd6, 0x99, 0x7b, 0xce, 0xb9, 0xf7, 0x9c, 0x99, 0x29,
	0xf0, 0x30, 0x13, 0x4b, 0x2f, 0x8c, 0x07, 0xf3, 0x95, 0x90, 0x03, 0x3a, 0xa7, 0x48, 0x7a, 0xdb,
	0x24, 0x96, 0x31, 0x76, 0xf2, 0x8a, 0xa7, 0x2a, 0xee, 0xe1, 0x32, 0x8e, 0x97, 0x6b, 0x1a, 0xe8,
	0xda, 0x6c, 0xb7, 0x18, 0xc8, 0x70, 0x43, 0xa9, 0x14, 0x9b, 0xad, 0x81, 0xbb, 0x7b, 0x42, 0x91,
	0x4c, 0x32, 0x53, 0xe9, 0x7d, 0x04, 0xe7, 0x44, 0xe9, 0xbe, 0x21, 0x29, 0x10, 0x81, 0xed, 0x76,
	0x61, 0xc0, 0x6b, 0xdd, 0x5a, 0xdf, 0xf1, 0xf5, 0x37, 0x7a, 0xc0, 0x94, 0x1a, 0xaf, 0x77, 0x6b,
	0xfd, 0xf6, 0xd0, 0xf5, 0x4c, 0x2b, 0xaf, 0x68, 0xe5, 0x9d, 0x15, 0xad, 0x7c, 0x8d, 0x43, 0x17,
	0x5a, 0x29, 0x7d, 0xda, 0x51, 0x34, 0x27, 0xde, 0xe8, 0xd6, 0xfa, 0xcc, 0x2f, 0xd7, 0xbd, 0x9f,
	0x75, 0xe8, 0x1c, 0xaf, 0x44, 0x14, 0xd1, 0xfa, 0x54, 0x0a, 0x49, 0xf8, 0x04, 0x60, 0x2d, 0x52,
	0x39, 0xd5, 0xd6, 0x74, 0xdb, 0xf6, 0xf0, 0x9a, 0x77, 0xd1, 0x9b, 0x57, 0x4e, 0xe7, 0x3b, 0x0a,
	0xaa, 0x97, 0xf8, 0x10, 0x6c, 0x65, 0x22, 0xa4, 0x94, 0xd7, 0xbb, 0x8d, 0x7e, 0x7b, 0x78, 0x75,
	0x8f, 0xa4, 0x1c, 0xfa, 0x05, 0x06, 0x6f, 0x02, 0x88, 0x9d, 0x5c, 0xc5, 0xc9, 0x34, 0x0c, 0x52,
	0xde, 0xe8, 0x36, 0xfa, 0x8e, 0xef, 0x98, 0x9d, 0x97, 0x41, 0x8a, 0x4f, 0x01, 0xe6, 0x09, 0x09,
	0x49, 0xc1, 0x54, 0x48, 0xce, 0x2a, 0x8d, 0x3a, 0x39, 0x7a, 0x24, 0xf1, 0x08, 0xda, 0x22, 0x99,
	0xaf, 0xc2, 0x73, 0xc3, 0x6d, 0x56, 0x72, 0xa1, 0x80, 0x8f, 0xa4, 0x1a, 0xab, 0xe8, 0x3b, 0xcb,
	0xb8, 0xa5, 0x43, 0x2f, 0xb4, 0xc7, 0x19, 0x1e, 0x5e, 0xd0, 0x9e, 0x65, 0xdc, 0xd6, 0xf5, 0x92,
	0x3f, 0xce, 0xd4, 0x71, 0x45, 0x62, 0x43, 0xbc, 0x65, 0x8e, 0x4b, 0x7d, 0xf7, 0x7e, 0x31, 0xb8,
	0x92, 0x47, 0xfc, 0x2e, 0xa5, 0xc4, 0xc4, 0xf5, 0x00, 0xd8, 0x86, 0xa4, 0xe0, 0xc1, 0xff, 0x03,
	0xd6, 0x20, 0xbc, 0x05, 0x9d, 0xb9, 0x11, 0x98, 0x6a, 0x75, 0xd2, 0xea, 0xed, 0x7c, 0xef, 0xad,
	0xd8, 0x10, 0x5e, 0x07, 0xa7, 0xcc, 0x93, 0x2f, 0x74, 0xbd, 0x55, 0xc4, 0x89, 0x63, 0xb0, 0x73,
	0x0f, 0xfc, 0xb3, 0x39, 0xd1, 0xbb, 0x7f, 0x37, 0xdc, 0x1f, 0xcf, 0x3b, 0xd6, 0xf0, 0xc9, 0x81,
	0x5f, 0x10, 0xf1, 0x04, 0x5a, 0x85, 0x4f, 0xfe, 0xc5, 0x88, 0xdc, 0xab, 0x10, 0x19, 0x19, 0xfc,
	0xe4, 0xc0, 0x2f, 0xa9, 0xf8, 0x02, 0xac, 0x0f, 0x71, 0x18, 0x51, 0xc0, 0xbf, 0x1a, 0x91, 0xdb,
	0x15, 0x22, 0xaf, 0xe2, 0x30, 0x9a, 0x1c, 0xf8, 0x39, 0x0b, 0x8f, 0x80, 0xad, 0x69, 0x21, 0xf9,
	0x37, 0xc3, 0xbe, 0x53, 0xc1, 0x7e, 0x4d, 0x42, 0x0f, 0xa0, 0x49, 0xf8, 0x1c, 0x9a, 0x32, 0xdb,
	0x52, 0xc0, 0xbf, 0x5f, 0xae, 0xf7, 0x59, 0xb6, 0x55, 0x64, 0x43, 0xc2, 0x67, 0xc0, 0x52, 0xf5,
	0x26, 0x7e, 0x5c, 0x8e, 0x7c, 0x4a, 0x51, 0xa0, 0x3a, 0x2b, 0x8e, 0x7b, 0x03, 0x2c, 0x13, 0x69,
	0x79, 0x43, 0x6a, 0x7f, 0x6e, 0x88, 0xeb, 0x80, 0x9d, 0x67, 0xe5, 0x5a, 0xc0, 0x94, 0x63, 0xd7,
	0x86, 0xa6, 0x9e, 0x5d, 0x6d, 0xa8, 0x31, 0xdc, 0x47, 0xc0, 0x94, 0x22, 0xde, 0x87, 0xa6, 0xfe,
	0x59, 0xe4, 0x4f, 0xf3, 0x9f, 0xaf, 0xcc, 0x20, 0xc6, 0x36, 0x34, 0xf5, 0x2b, 0x1e, 0x5b, 0xef,
	0x99, 0xaa, 0xce, 0x2c, 0x7d, 0xfb, 0x1f, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xd2, 0xee, 0xd6,
	0xf2, 0xc5, 0x04, 0x00, 0x00,
}
